homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /admin
        permanent: true

# lexik/jwt-authentication-bundle
api_login_check:
    path: /api/login_check
    
#   
#fos_js_routing:
#    resource: "Symfony\Bundle\friendsofsymfony\jsrouting-Bundle\Resources\config\routing\routing.xml"
#    